name: Run Postman Tests with Allure Report

on:
  push:
    branches:
      - master
  workflow_dispatch:  # to run workflow from UI

jobs:
  run-tests:
    name: Run Newman API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Newman tests
        run: npm run test:api

      - name: Generate Allure report
        run: npm run report:allure

      - name: Archive Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report/